name: NAIA CI/CD

on:
  push:
    branches:
      - development
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: List files
        run: |
          echo "Listing files in the repository:"
          ls -R