name: NAIA Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    name: Deploy to VM
    runs-on: ubuntu-latest
    steps:
      - name: Call Deployment Webhook
        id: webhook
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d '{"token": "${{ secrets.DEPLOY_TOKEN }}"}' \
            -w "\n\nHTTP Status Code: %{http_code}" \
            ${{ secrets.WEBHOOK_URL }})
          
          # Mostrar la respuesta completa
          echo "Respuesta del servidor:"
          echo "$RESPONSE"
          
          # Verificar si la respuesta contiene un código de éxito (200)
          if [[ "$RESPONSE" == *"HTTP Status Code: 200"* ]]; then
            echo "✅ Solicitud de despliegue procesada exitosamente"
          else
            echo "⚠️ La solicitud no retornó un código 200. Verifica el estado del servidor"
            echo "Detalles en los logs de GitHub Actions"
          fi