name: NAIA Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    name: Deploy to VM
    runs-on: ubuntu-latest
    steps:
      - name: Call Deployment Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"token": "${{ secrets.DEPLOY_TOKEN }}"}' \
            ${{ secrets.WEBHOOK_URL }}
      
      - name: Verify Deployment Status
        run: |
          echo "Solicitud de despliegue enviada"
          echo "Verifica el estado en tu servidor de despliegue"